version: "3"
services:
  reverseproxy:
      image: ahmedaltour/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: ahmedaltour/udacity-restapi-user
    environment:
      POSTGRESS_USERNAME: "udagramaltourdev"
      POSTGRESS_PASSWORD: "udagramaltourdev"
      POSTGRESS_DB: "udagramaltourdev"
      POSTGRESS_HOST: "udagramaltourdev.cenihmh40szt.us-east-1.rds.amazonaws.com"
      AWS_REGION: "us-east-1"
      AWS_PROFILE: "default"
      AWS_BUCKET: "udagram-altour-dev"
      JWT_SECRET: "helloworld"
      URL: "http://localhost:8100"
  backend-feed:
    image: ahmedaltour/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: "udagramaltourdev"
      POSTGRESS_PASSWORD: "udagramaltourdev"
      POSTGRESS_DB: "udagramaltourdev"
      POSTGRESS_HOST: "udagramaltourdev.cenihmh40szt.us-east-1.rds.amazonaws.com"
      AWS_REGION: "us-east-1"
      AWS_PROFILE: "default"
      AWS_BUCKET: "udagram-altour-dev"
      JWT_SECRET: "helloworld"
      URL: "http://localhost:8100"
  frontend:
    image: ahmedaltour/udacity-frontend:local
    ports:
      - "8100:80"
